# Generated by Django 2.2.7 on 2019-12-26 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSmartId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'business_smart_id',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('legal_address', models.CharField(max_length=100, verbose_name='Юридический адрес')),
                ('inn', models.CharField(max_length=100, verbose_name='ИНН')),
                ('ogrn', models.CharField(max_length=100, verbose_name='ОГРН')),
                ('kpp', models.CharField(max_length=100, verbose_name='КПП')),
                ('ceo', models.CharField(max_length=100, verbose_name='CEO')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название специализации')),
            ],
        ),
        migrations.CreateModel(
            name='SmartId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('status', models.IntegerField(choices=[(0, 'Физическое лицо'), (1, 'Самозанятый'), (2, 'Официально работающий')], default=0, verbose_name='Статус физического лица')),
                ('passport_scan', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Скан паспорта')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Specialization', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'smart_id',
            },
        ),
    ]
