# Generated by Django 2.2.7 on 2019-12-26 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smartid',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт'),
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт'),
        ),
        migrations.AddField(
            model_name='businesssmartid',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounts.Company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='businesssmartid',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Specialization', verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='businesssmartid',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт'),
        ),
    ]
