# Generated by Django 2.2.7 on 2019-12-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191224_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='passport_scan',
        ),
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Подтверджённый аккаунт'),
        ),
        migrations.AddField(
            model_name='smartid',
            name='passport_scan',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Скан паспорта'),
        ),
    ]
